# sources, headers
set(GAME_HEADER
	${RUNTIME_SRC_ROOT}/Classes/Classes/ArrayObjectPool.hpp
	${RUNTIME_SRC_ROOT}/Classes/Classes/XThreadPool.hpp
	${RUNTIME_SRC_ROOT}/Classes/Classes/ControllerHelper.h
	${RUNTIME_SRC_ROOT}/Classes/Classes/LabelPool.h
	${RUNTIME_SRC_ROOT}/Classes/Classes/MemPoolManager.h
	${RUNTIME_SRC_ROOT}/Classes/Classes/RandomWELL512.h
	${RUNTIME_SRC_ROOT}/Classes/Classes/WindowHelper.h
	${RUNTIME_SRC_ROOT}/Classes/Classes/XBinaryHelper.h
	${RUNTIME_SRC_ROOT}/Classes/Classes/XBuffer.h
	${RUNTIME_SRC_ROOT}/Classes/Classes/XFileDialog.h
	${RUNTIME_SRC_ROOT}/Classes/Classes/XFileUtils.h
	${RUNTIME_SRC_ROOT}/Classes/Classes/XGifRecoder.h
	${RUNTIME_SRC_ROOT}/Classes/Classes/XLabel.h
	${RUNTIME_SRC_ROOT}/Classes/Classes/XLatex.h
	${RUNTIME_SRC_ROOT}/Classes/Classes/XLuaModuleRegistry.h
	${RUNTIME_SRC_ROOT}/Classes/Classes/XProfiler.h
	${RUNTIME_SRC_ROOT}/Classes/Classes/XRand.h
	${RUNTIME_SRC_ROOT}/Classes/Classes/XRefAdapter.h
	${RUNTIME_SRC_ROOT}/Classes/Classes/XStopWatch.h
	${RUNTIME_SRC_ROOT}/Classes/Classes/XStream.h
	${RUNTIME_SRC_ROOT}/Classes/Classes/XTriangles.h
	${RUNTIME_SRC_ROOT}/Classes/Classes/XTrianglesCommand.h
	${RUNTIME_SRC_ROOT}/Classes/Classes/XZipArchive.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/CirularQueue.hpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/Dictionary.hpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ObjectPool.hpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/AppFrame.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/CollisionDetect.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ComponentData.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ComponentDataAni.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ComponentDataBlend.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ComponentDataColli.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ComponentDataLabel.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ComponentDataLight.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ComponentDataParticle.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ComponentDataTrasform.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ComponentDataVertex.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ComponentManager.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/GameClass.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/GameObject.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/GameObjectBentLaser.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/GameObjectManager.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/GameObjectPool.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/GameObjectPropertyHash.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/GameObjectSymbol.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/GameResources.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/Global.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/GOSymbolBoolean.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/GOSymbolNumber.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/InputManager.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/LogSystem.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/LuaWrapper.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/LWBuiltInFunction.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/LWColor.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/LWProfiler.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/LWRandomizer.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/LW_Frame.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/LW_Graph.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/LW_Input.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/LW_Math.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/LW_Object.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/LW_Render.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/LW_Text.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/Renderer.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/RenderMode.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ResAnimation.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ResAudio.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ResBase.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ResFont.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ResFX.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ResourceMgr.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ResParticle.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ResRenderTarget.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ResSprite.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ResTexture.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/UtilColor.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/UtilGLDefinition.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/Utility.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/UtilLua.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/UtilLuaConversion.h
	${RUNTIME_SRC_ROOT}/Classes/LSTG/UtilLuaRes.h
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_BentLaser_auto.hpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_Buffer_auto.hpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_cc_controller_auto.hpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_cc_controller_manual.hpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_cc_ext.hpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_cc_fix.h
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_FileDialog_auto.hpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_Latex_auto.hpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_LogSystem_auto.hpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_ObjSym_auto.hpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_ParticlePool_auto.hpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_Random_auto.hpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_RenderMode_auto.hpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_ResourceMgr_auto.hpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_Resource_auto.hpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_StopWatch_auto.hpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_Stream_auto.hpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_Triangles_auto.hpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_WindowHelper_auto.hpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_ZipArchive_auto.hpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/LuaBindings.h
)
set(GAME_SOURCE
	${RUNTIME_SRC_ROOT}/Classes/Classes/ControllerHelper.cpp
	${RUNTIME_SRC_ROOT}/Classes/Classes/LabelPool.cpp
	${RUNTIME_SRC_ROOT}/Classes/Classes/MemPoolManager.cpp
	${RUNTIME_SRC_ROOT}/Classes/Classes/RandomWELL512.cpp
	${RUNTIME_SRC_ROOT}/Classes/Classes/WindowHelper.cpp
	${RUNTIME_SRC_ROOT}/Classes/Classes/XBinaryHelper.cpp
	${RUNTIME_SRC_ROOT}/Classes/Classes/XBuffer.cpp
	${RUNTIME_SRC_ROOT}/Classes/Classes/XFileDialog.cpp
	${RUNTIME_SRC_ROOT}/Classes/Classes/XFileUtils.cpp
	${RUNTIME_SRC_ROOT}/Classes/Classes/XGifRecoder.cpp
	${RUNTIME_SRC_ROOT}/Classes/Classes/XLabel.cpp
	${RUNTIME_SRC_ROOT}/Classes/Classes/XLatex.cpp
	${RUNTIME_SRC_ROOT}/Classes/Classes/XLuaModuleRegistry.cpp
	${RUNTIME_SRC_ROOT}/Classes/Classes/XProfiler.cpp
	${RUNTIME_SRC_ROOT}/Classes/Classes/XRand.cpp
	${RUNTIME_SRC_ROOT}/Classes/Classes/XRefAdapter.cpp
	${RUNTIME_SRC_ROOT}/Classes/Classes/XStopWatch.cpp
	${RUNTIME_SRC_ROOT}/Classes/Classes/XStream.cpp
	${RUNTIME_SRC_ROOT}/Classes/Classes/XTriangles.cpp
	${RUNTIME_SRC_ROOT}/Classes/Classes/XTrianglesCommand.cpp
	${RUNTIME_SRC_ROOT}/Classes/Classes/XZipArchive.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/AppFrame.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/CollisionDetect.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ComponentData.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ComponentDataAni.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ComponentDataBlend.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ComponentDataColli.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ComponentDataLabel.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ComponentDataLight.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ComponentDataParticle.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ComponentDataTrasform.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ComponentDataVertex.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ComponentManager.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/GameClass.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/GameObject.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/GameObjectBentLaser.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/GameObjectManager.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/GameObjectPool.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/GameObjectPropertyHash.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/GameObjectSymbol.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/GOSymbolBoolean.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/GOSymbolNumber.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/InputManager.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/LogSystem.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/LuaWrapper.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/LWBuiltInFunction.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/LWColor.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/LWProfiler.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/LWRandomizer.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/LW_Frame.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/LW_Graph.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/LW_Input.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/LW_Math.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/LW_Object.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/LW_Render.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/LW_Text.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/Renderer.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/RenderMode.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ResAnimation.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ResAudio.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ResBase.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ResFont.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ResFX.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ResourceMgr.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ResParticle.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ResRenderTarget.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ResSprite.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/ResTexture.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/UtilColor.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/UtilGLDefinition.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/Utility.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/UtilLua.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/UtilLuaConversion.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/UtilLuaRes.cpp
	${RUNTIME_SRC_ROOT}/Classes/LSTG/UtilShader.cpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_BentLaser_auto.cpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_Buffer_auto.cpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_cc_controller_auto.cpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_cc_controller_manual.cpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_cc_ext.cpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_cc_fix.cpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_FileDialog_auto.cpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_Latex_auto.cpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_LogSystem_auto.cpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_ObjSym_auto.cpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_ParticlePool_auto.cpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_Random_auto.cpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_RenderMode_auto.cpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_ResourceMgr_auto.cpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_Resource_auto.cpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_StopWatch_auto.cpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_Stream_auto.cpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_Triangles_auto.cpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_WindowHelper_auto.cpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/lua_ZipArchive_auto.cpp
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings/LuaBindings.cpp
)

# sources need to compile info, include dirs and source files
set(GAME_INCLUDE
	${RUNTIME_SRC_ROOT}/Classes
	${RUNTIME_SRC_ROOT}/Classes/Audio
	${RUNTIME_SRC_ROOT}/Classes/Classes
	${RUNTIME_SRC_ROOT}/Classes/imgui
	${RUNTIME_SRC_ROOT}/Classes/Live2D
	${RUNTIME_SRC_ROOT}/Classes/LSTG
	${RUNTIME_SRC_ROOT}/Classes/LuaBindings
	${RUNTIME_SRC_ROOT}/Classes/Math
	${RUNTIME_SRC_ROOT}/Classes/reader
	${RUNTIME_SRC_ROOT}/Classes/Video
)

if(ANDROID)
	list(APPEND GAME_SOURCE ${RUNTIME_SRC_ROOT}/proj.android/app/jni/hellolua/main.cpp)
elseif(LINUX)
    list(APPEND GAME_SOURCE ${RUNTIME_SRC_ROOT}/proj.linux/main.cpp)
elseif(IOS)
	set(APP_UI_RES
		${RUNTIME_SRC_ROOT}/proj.ios_mac/ios/LaunchScreen.storyboard
		${RUNTIME_SRC_ROOT}/proj.ios_mac/ios/LaunchScreenBackground.png
		${RUNTIME_SRC_ROOT}/proj.ios_mac/ios/Images.xcassets
	)
	list(APPEND GAME_HEADER
        ${RUNTIME_SRC_ROOT}/proj.ios_mac/ios/AppController.h
        ${RUNTIME_SRC_ROOT}/proj.ios_mac/ios/RootViewController.h
	)
	list(APPEND GAME_SOURCE
		${RUNTIME_SRC_ROOT}/proj.ios_mac/ios/main.m
		${RUNTIME_SRC_ROOT}/proj.ios_mac/ios/AppController.mm
		${RUNTIME_SRC_ROOT}/proj.ios_mac/ios/RootViewController.mm
		${RUNTIME_SRC_ROOT}/proj.ios_mac/ios/Prefix.pch
		${RUNTIME_SRC_ROOT}/proj.ios_mac/ios/build-cfg.json
		${APP_UI_RES}
	)
elseif(MACOSX)
	set(APP_UI_RES
		${RUNTIME_SRC_ROOT}/proj.ios_mac/mac/Icon.icns
		${RUNTIME_SRC_ROOT}/proj.ios_mac/mac/Info.plist
	)
	list(APPEND GAME_SOURCE
		${RUNTIME_SRC_ROOT}/proj.ios_mac/mac/main.mm
		${RUNTIME_SRC_ROOT}/proj.ios_mac/mac/ConsoleWindowController.m
		${RUNTIME_SRC_ROOT}/proj.ios_mac/mac/Prefix.pch
		${APP_UI_RES}
	)
elseif(WINDOWS)
    list(APPEND GAME_HEADER
		${RUNTIME_SRC_ROOT}/proj.win32/main.h
		${RUNTIME_SRC_ROOT}/proj.win32/resource.h
        ${RUNTIME_SRC_ROOT}/proj.win32/WindowHelperWin32.h
    )
    list(APPEND GAME_SOURCE ${cc_common_res})
    list(APPEND GAME_SOURCE
		${RUNTIME_SRC_ROOT}/proj.win32/main.cpp
		${RUNTIME_SRC_ROOT}/proj.win32/game.rc
        ${RUNTIME_SRC_ROOT}/proj.win32/WindowHelperWin32.cpp
    )
endif()
