# sources, headers
set(LSTGX_SRC_ROOT ${CMAKE_CURRENT_SOURCE_DIR}/frameworks)
set(GAME_HEADER
	${LSTGX_SRC_ROOT}/Classes/ArrayObjectPool.hpp
	${LSTGX_SRC_ROOT}/Classes/XThreadPool.hpp
	${LSTGX_SRC_ROOT}/Classes/ControllerHelper.h
	${LSTGX_SRC_ROOT}/Classes/LabelPool.h
	${LSTGX_SRC_ROOT}/Classes/MemPoolManager.h
	${LSTGX_SRC_ROOT}/Classes/RandomWELL512.h
	${LSTGX_SRC_ROOT}/Classes/WindowHelper.h
	${LSTGX_SRC_ROOT}/Classes/XBinaryHelper.h
	${LSTGX_SRC_ROOT}/Classes/XBuffer.h
	${LSTGX_SRC_ROOT}/Classes/XFileDialog.h
	${LSTGX_SRC_ROOT}/Classes/XFileUtils.h
	${LSTGX_SRC_ROOT}/Classes/XGifRecoder.h
	${LSTGX_SRC_ROOT}/Classes/XInfoware.h
	${LSTGX_SRC_ROOT}/Classes/XLabel.h
	${LSTGX_SRC_ROOT}/Classes/XLatex.h
	${LSTGX_SRC_ROOT}/Classes/XLuaModuleRegistry.h
	${LSTGX_SRC_ROOT}/Classes/XProfiler.h
	${LSTGX_SRC_ROOT}/Classes/XRand.h
	${LSTGX_SRC_ROOT}/Classes/XRefAdapter.h
	${LSTGX_SRC_ROOT}/Classes/XStopWatch.h
	${LSTGX_SRC_ROOT}/Classes/XStream.h
	${LSTGX_SRC_ROOT}/Classes/XTriangles.h
	${LSTGX_SRC_ROOT}/Classes/XTrianglesCommand.h
	${LSTGX_SRC_ROOT}/Classes/XZipArchive.h
	${LSTGX_SRC_ROOT}/LSTG/CirularQueue.hpp
	${LSTGX_SRC_ROOT}/LSTG/Dictionary.hpp
	${LSTGX_SRC_ROOT}/LSTG/ObjectPool.hpp
	${LSTGX_SRC_ROOT}/LSTG/AppFrame.h
	${LSTGX_SRC_ROOT}/LSTG/CollisionDetect.h
	${LSTGX_SRC_ROOT}/LSTG/ComponentData.h
	${LSTGX_SRC_ROOT}/LSTG/ComponentDataAni.h
	${LSTGX_SRC_ROOT}/LSTG/ComponentDataBlend.h
	${LSTGX_SRC_ROOT}/LSTG/ComponentDataColli.h
	${LSTGX_SRC_ROOT}/LSTG/ComponentDataLabel.h
	${LSTGX_SRC_ROOT}/LSTG/ComponentDataLight.h
	${LSTGX_SRC_ROOT}/LSTG/ComponentDataParticle.h
	${LSTGX_SRC_ROOT}/LSTG/ComponentDataTrasform.h
	${LSTGX_SRC_ROOT}/LSTG/ComponentDataVertex.h
	${LSTGX_SRC_ROOT}/LSTG/ComponentManager.h
	${LSTGX_SRC_ROOT}/LSTG/GameClass.h
	${LSTGX_SRC_ROOT}/LSTG/GameObject.h
	${LSTGX_SRC_ROOT}/LSTG/GameObjectBentLaser.h
	${LSTGX_SRC_ROOT}/LSTG/GameObjectManager.h
	${LSTGX_SRC_ROOT}/LSTG/GameObjectPool.h
	${LSTGX_SRC_ROOT}/LSTG/GameObjectPropertyHash.h
	${LSTGX_SRC_ROOT}/LSTG/GameObjectSymbol.h
	${LSTGX_SRC_ROOT}/LSTG/GameResources.h
	${LSTGX_SRC_ROOT}/LSTG/Global.h
	${LSTGX_SRC_ROOT}/LSTG/GOSymbolBoolean.h
	${LSTGX_SRC_ROOT}/LSTG/GOSymbolNumber.h
	${LSTGX_SRC_ROOT}/LSTG/InputManager.h
	${LSTGX_SRC_ROOT}/LSTG/LogSystem.h
	${LSTGX_SRC_ROOT}/LSTG/LuaWrapper.h
	${LSTGX_SRC_ROOT}/LSTG/LWBuiltInFunction.h
	${LSTGX_SRC_ROOT}/LSTG/LWColor.h
	${LSTGX_SRC_ROOT}/LSTG/LWProfiler.h
	${LSTGX_SRC_ROOT}/LSTG/LWRandomizer.h
	${LSTGX_SRC_ROOT}/LSTG/LW_Frame.h
	${LSTGX_SRC_ROOT}/LSTG/LW_Graph.h
	${LSTGX_SRC_ROOT}/LSTG/LW_Input.h
	${LSTGX_SRC_ROOT}/LSTG/LW_Math.h
	${LSTGX_SRC_ROOT}/LSTG/LW_Object.h
	${LSTGX_SRC_ROOT}/LSTG/LW_Render.h
	${LSTGX_SRC_ROOT}/LSTG/LW_Text.h
	${LSTGX_SRC_ROOT}/LSTG/Renderer.h
	${LSTGX_SRC_ROOT}/LSTG/RenderMode.h
	${LSTGX_SRC_ROOT}/LSTG/ResAnimation.h
	${LSTGX_SRC_ROOT}/LSTG/ResAudio.h
	${LSTGX_SRC_ROOT}/LSTG/ResBase.h
	${LSTGX_SRC_ROOT}/LSTG/ResFont.h
	${LSTGX_SRC_ROOT}/LSTG/ResFX.h
	${LSTGX_SRC_ROOT}/LSTG/ResourceMgr.h
	${LSTGX_SRC_ROOT}/LSTG/ResParticle.h
	${LSTGX_SRC_ROOT}/LSTG/ResRenderTarget.h
	${LSTGX_SRC_ROOT}/LSTG/ResSprite.h
	${LSTGX_SRC_ROOT}/LSTG/ResTexture.h
	${LSTGX_SRC_ROOT}/LSTG/UtilColor.h
	${LSTGX_SRC_ROOT}/LSTG/UtilGLDefinition.h
	${LSTGX_SRC_ROOT}/LSTG/Utility.h
	${LSTGX_SRC_ROOT}/LSTG/UtilLua.h
	${LSTGX_SRC_ROOT}/LSTG/UtilLuaConversion.h
	${LSTGX_SRC_ROOT}/LSTG/UtilLuaRes.h
	${LSTGX_SRC_ROOT}/LuaBindings/lua_BentLaser_auto.hpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_Buffer_auto.hpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_cc_configuration_auto.hpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_cc_controller_auto.hpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_cc_controller_manual.hpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_cc_ext.hpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_cc_fix.h
	${LSTGX_SRC_ROOT}/LuaBindings/lua_FileDialog_auto.hpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_Latex_auto.hpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_LogSystem_auto.hpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_ObjSym_auto.hpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_ParticlePool_auto.hpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_Random_auto.hpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_RenderMode_auto.hpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_ResourceMgr_auto.hpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_Resource_auto.hpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_StopWatch_auto.hpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_Stream_auto.hpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_Triangles_auto.hpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_WindowHelper_auto.hpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_ZipArchive_auto.hpp
	${LSTGX_SRC_ROOT}/LuaBindings/LuaBindings.h
)
set(GAME_SOURCE
	${LSTGX_SRC_ROOT}/Classes/ControllerHelper.cpp
	${LSTGX_SRC_ROOT}/Classes/LabelPool.cpp
	${LSTGX_SRC_ROOT}/Classes/MemPoolManager.cpp
	${LSTGX_SRC_ROOT}/Classes/RandomWELL512.cpp
	${LSTGX_SRC_ROOT}/Classes/WindowHelper.cpp
	${LSTGX_SRC_ROOT}/Classes/XBinaryHelper.cpp
	${LSTGX_SRC_ROOT}/Classes/XBuffer.cpp
	${LSTGX_SRC_ROOT}/Classes/XFileDialog.cpp
	${LSTGX_SRC_ROOT}/Classes/XFileUtils.cpp
	${LSTGX_SRC_ROOT}/Classes/XGifRecoder.cpp
	${LSTGX_SRC_ROOT}/Classes/XInfoware.cpp
	${LSTGX_SRC_ROOT}/Classes/XLabel.cpp
	${LSTGX_SRC_ROOT}/Classes/XLatex.cpp
	${LSTGX_SRC_ROOT}/Classes/XLuaModuleRegistry.cpp
	${LSTGX_SRC_ROOT}/Classes/XProfiler.cpp
	${LSTGX_SRC_ROOT}/Classes/XRand.cpp
	${LSTGX_SRC_ROOT}/Classes/XRefAdapter.cpp
	${LSTGX_SRC_ROOT}/Classes/XStopWatch.cpp
	${LSTGX_SRC_ROOT}/Classes/XStream.cpp
	${LSTGX_SRC_ROOT}/Classes/XTriangles.cpp
	${LSTGX_SRC_ROOT}/Classes/XTrianglesCommand.cpp
	${LSTGX_SRC_ROOT}/Classes/XZipArchive.cpp
	${LSTGX_SRC_ROOT}/LSTG/AppFrame.cpp
	${LSTGX_SRC_ROOT}/LSTG/CollisionDetect.cpp
	${LSTGX_SRC_ROOT}/LSTG/ComponentData.cpp
	${LSTGX_SRC_ROOT}/LSTG/ComponentDataAni.cpp
	${LSTGX_SRC_ROOT}/LSTG/ComponentDataBlend.cpp
	${LSTGX_SRC_ROOT}/LSTG/ComponentDataColli.cpp
	${LSTGX_SRC_ROOT}/LSTG/ComponentDataLabel.cpp
	${LSTGX_SRC_ROOT}/LSTG/ComponentDataLight.cpp
	${LSTGX_SRC_ROOT}/LSTG/ComponentDataParticle.cpp
	${LSTGX_SRC_ROOT}/LSTG/ComponentDataTrasform.cpp
	${LSTGX_SRC_ROOT}/LSTG/ComponentDataVertex.cpp
	${LSTGX_SRC_ROOT}/LSTG/ComponentManager.cpp
	${LSTGX_SRC_ROOT}/LSTG/GameClass.cpp
	${LSTGX_SRC_ROOT}/LSTG/GameObject.cpp
	${LSTGX_SRC_ROOT}/LSTG/GameObjectBentLaser.cpp
	${LSTGX_SRC_ROOT}/LSTG/GameObjectManager.cpp
	${LSTGX_SRC_ROOT}/LSTG/GameObjectPool.cpp
	${LSTGX_SRC_ROOT}/LSTG/GameObjectPropertyHash.cpp
	${LSTGX_SRC_ROOT}/LSTG/GameObjectSymbol.cpp
	${LSTGX_SRC_ROOT}/LSTG/GOSymbolBoolean.cpp
	${LSTGX_SRC_ROOT}/LSTG/GOSymbolNumber.cpp
	${LSTGX_SRC_ROOT}/LSTG/InputManager.cpp
	${LSTGX_SRC_ROOT}/LSTG/LogSystem.cpp
	${LSTGX_SRC_ROOT}/LSTG/LuaWrapper.cpp
	${LSTGX_SRC_ROOT}/LSTG/LWBuiltInFunction.cpp
	${LSTGX_SRC_ROOT}/LSTG/LWColor.cpp
	${LSTGX_SRC_ROOT}/LSTG/LWProfiler.cpp
	${LSTGX_SRC_ROOT}/LSTG/LWRandomizer.cpp
	${LSTGX_SRC_ROOT}/LSTG/LW_Frame.cpp
	${LSTGX_SRC_ROOT}/LSTG/LW_Graph.cpp
	${LSTGX_SRC_ROOT}/LSTG/LW_Input.cpp
	${LSTGX_SRC_ROOT}/LSTG/LW_Math.cpp
	${LSTGX_SRC_ROOT}/LSTG/LW_Object.cpp
	${LSTGX_SRC_ROOT}/LSTG/LW_Render.cpp
	${LSTGX_SRC_ROOT}/LSTG/LW_Text.cpp
	${LSTGX_SRC_ROOT}/LSTG/Renderer.cpp
	${LSTGX_SRC_ROOT}/LSTG/RenderMode.cpp
	${LSTGX_SRC_ROOT}/LSTG/ResAnimation.cpp
	${LSTGX_SRC_ROOT}/LSTG/ResAudio.cpp
	${LSTGX_SRC_ROOT}/LSTG/ResBase.cpp
	${LSTGX_SRC_ROOT}/LSTG/ResFont.cpp
	${LSTGX_SRC_ROOT}/LSTG/ResFX.cpp
	${LSTGX_SRC_ROOT}/LSTG/ResourceMgr.cpp
	${LSTGX_SRC_ROOT}/LSTG/ResParticle.cpp
	${LSTGX_SRC_ROOT}/LSTG/ResRenderTarget.cpp
	${LSTGX_SRC_ROOT}/LSTG/ResSprite.cpp
	${LSTGX_SRC_ROOT}/LSTG/ResTexture.cpp
	${LSTGX_SRC_ROOT}/LSTG/UtilColor.cpp
	${LSTGX_SRC_ROOT}/LSTG/UtilGLDefinition.cpp
	${LSTGX_SRC_ROOT}/LSTG/Utility.cpp
	${LSTGX_SRC_ROOT}/LSTG/UtilLua.cpp
	${LSTGX_SRC_ROOT}/LSTG/UtilLuaConversion.cpp
	${LSTGX_SRC_ROOT}/LSTG/UtilLuaRes.cpp
	${LSTGX_SRC_ROOT}/LSTG/UtilShader.cpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_BentLaser_auto.cpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_Buffer_auto.cpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_cc_configuration_auto.cpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_cc_controller_auto.cpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_cc_controller_manual.cpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_cc_ext.cpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_cc_fix.cpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_FileDialog_auto.cpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_Latex_auto.cpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_LogSystem_auto.cpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_ObjSym_auto.cpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_ParticlePool_auto.cpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_Random_auto.cpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_RenderMode_auto.cpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_ResourceMgr_auto.cpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_Resource_auto.cpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_StopWatch_auto.cpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_Stream_auto.cpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_Triangles_auto.cpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_WindowHelper_auto.cpp
	${LSTGX_SRC_ROOT}/LuaBindings/lua_ZipArchive_auto.cpp
	${LSTGX_SRC_ROOT}/LuaBindings/LuaBindings.cpp
)

# sources need to compile info, include dirs and source files
set(GAME_INCLUDE
	${LSTGX_SRC_ROOT}
	${LSTGX_SRC_ROOT}/Audio
	${LSTGX_SRC_ROOT}/Classes
	${LSTGX_SRC_ROOT}/imgui
	${LSTGX_SRC_ROOT}/Live2D
	${LSTGX_SRC_ROOT}/LSTG
	${LSTGX_SRC_ROOT}/LuaBindings
	${LSTGX_SRC_ROOT}/Math
	${LSTGX_SRC_ROOT}/reader
	${LSTGX_SRC_ROOT}/Video
)

if(ANDROID)
	list(APPEND GAME_SOURCE ${RUNTIME_SRC_ROOT}/proj.android/app/jni/hellolua/main.cpp)
elseif(LINUX)
    list(APPEND GAME_SOURCE ${RUNTIME_SRC_ROOT}/proj.linux/main.cpp)
elseif(IOS)
	set(APP_UI_RES
		${RUNTIME_SRC_ROOT}/proj.ios_mac/ios/LaunchScreen.storyboard
		${RUNTIME_SRC_ROOT}/proj.ios_mac/ios/LaunchScreenBackground.png
		${RUNTIME_SRC_ROOT}/proj.ios_mac/ios/Images.xcassets
	)
	list(APPEND GAME_HEADER
        ${RUNTIME_SRC_ROOT}/proj.ios_mac/ios/AppController.h
        ${RUNTIME_SRC_ROOT}/proj.ios_mac/ios/RootViewController.h
	)
	list(APPEND GAME_SOURCE
		${RUNTIME_SRC_ROOT}/proj.ios_mac/ios/main.m
		${RUNTIME_SRC_ROOT}/proj.ios_mac/ios/AppController.mm
		${RUNTIME_SRC_ROOT}/proj.ios_mac/ios/RootViewController.mm
		${RUNTIME_SRC_ROOT}/proj.ios_mac/ios/Prefix.pch
		${RUNTIME_SRC_ROOT}/proj.ios_mac/ios/build-cfg.json
		${APP_UI_RES}
	)
elseif(MACOSX)
	set(APP_UI_RES
		${RUNTIME_SRC_ROOT}/proj.ios_mac/mac/Icon.icns
		${RUNTIME_SRC_ROOT}/proj.ios_mac/mac/Info.plist
	)
	list(APPEND GAME_SOURCE
		${RUNTIME_SRC_ROOT}/proj.ios_mac/mac/main.mm
		${RUNTIME_SRC_ROOT}/proj.ios_mac/mac/ConsoleWindowController.m
		${RUNTIME_SRC_ROOT}/proj.ios_mac/mac/Prefix.pch
		${APP_UI_RES}
	)
elseif(WINDOWS)
    list(APPEND GAME_HEADER
		${RUNTIME_SRC_ROOT}/proj.win32/main.h
		${RUNTIME_SRC_ROOT}/proj.win32/resource.h
        ${RUNTIME_SRC_ROOT}/proj.win32/WindowHelperWin32.h
    )
    list(APPEND GAME_SOURCE ${cc_common_res})
    list(APPEND GAME_SOURCE
		${RUNTIME_SRC_ROOT}/proj.win32/main.cpp
		${RUNTIME_SRC_ROOT}/proj.win32/game.rc
        ${RUNTIME_SRC_ROOT}/proj.win32/WindowHelperWin32.cpp
    )
endif()
